# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

repository: mcdeck/mcdeck.github.io

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Oliver van Porten
email: oliver@van-porten.de
description: >- # this means to ignore newlines until "baseurl:"
  [![](https://i.creativecommons.org/l/by-sa/4.0/88x31.png)](http://creativecommons.org/licenses/by-sa/4.0/) 

  This work is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.van-porten.de" # the base hostname & protocol for your site, e.g. http://example.com

# Social accounts
twitter_username: mcdeck
github_username:  mcdeck
facebook_username: ovanporten
flickr_username: mcdeck
instagram_username: mcdeck
linkedin_username: ovanporten
pinterest_username: ovanporten
youtube_username: mcdeck
googleplus_username: +OlivervanPorten
rss: rss

header_pages:
  - _pages/blog.md
  - _pages/portfolio.md
  - _pages/about.md
  - _pages/contact.md
  - _pages/datenschutz.md
  - _pages/imprint.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-include-cache

show_excerpts: false

kramdown:
  input: GFM
  syntax_highlighter: rouge

disqus:
  shortname: porten

google_analytics: UA-18665649-3

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:title/
  pages:
    output: true
    permalink: /:title/
  portfolio:
    output: true
    permalink: /portfolio/:title/
